CREATE TABLE IF NOT EXISTS mpa_rating (
     id INTEGER PRIMARY KEY,
     name VARCHAR(200) NOT NULL,
     description VARCHAR(200)
     );

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(200),
    duration INTEGER NOT NULL,
    release_date DATE NOT NULL,
    mpa_rating_id INTEGER,
    CONSTRAINT fk_films_mpa_rating FOREIGN KEY (mpa_rating_id) REFERENCES mpa_rating(id)
    );

CREATE TABLE IF NOT EXISTS genres (
     id INTEGER PRIMARY KEY,
     name VARCHAR(200) NOT NULL UNIQUE,
     description VARCHAR(200)
     );

CREATE TABLE IF NOT EXISTS film_genres (
    film_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_film_genre_film FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    CONSTRAINT fk_film_genre_genre FOREIGN KEY (genre_id) REFERENCES genres(id)
    );

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(200) NOT NULL UNIQUE,
    login VARCHAR(200) NOT NULL,
    name VARCHAR(200) NOT NULL,
    birthday DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS film_like (
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_film_like_film FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    CONSTRAINT fk_film_like_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS users_friends (
    user_id INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_users_friends_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_users_friends_friend FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE
);